<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMEVdgtk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMEVdgtk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMEVdgtk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMEVdgtk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMEVdgtk\App_KernelDevDebugContainer([
    'container.build_hash' => 'MEVdgtk',
    'container.build_id' => 'c40cc0a8',
    'container.build_time' => 1646007522,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMEVdgtk');
